spire 1.5 in docker compose
anthem-ai/spire-docker-compose pull request #6
Opened 2022-12-22 18:25 UTC by foo-anthem

2022-12-22 18:30 UTC, adam-amr commented on k8s/example.values.yaml
> +  serviceType: NodePort
I think we could remove these since they are already in `values.yaml`

2022-12-22 18:30 UTC, adam-amr commented on k8s/example.values.yaml
> +  serviceType: NodePort
```suggestion
```

2022-12-22 18:31 UTC, adam-amr commented on k8s/README.md
> +new file (ie: `values.yaml`) and update all values that are set to `REPLACE_ME`:
`values.yaml` is the default values so if they overwrite their custom one to that it will break

2022-12-22 18:32 UTC, adam-amr commented on docker/README.md
> +
Missed this in the gitlab review but this step is actually not needed anymore since we have SSL on the DPOS side

2022-12-22 18:33 UTC, adam-amr requested changes
See some things we could strip out

2022-12-23 01:36 UTC, foo-anthem commented on k8s/example.values.yaml
> +  serviceType: NodePort
done

2023-01-04 19:53 UTC, adam-amr approved these changes

2023-01-04 19:53 UTC, merged